### ISSUE TITLE
.showPortis() is not a function

### ISSUE THREAD

**Issue by nceno** [portis-project/portis-sdk#17]
In the example, https://plnkr.co/edit/gHp1TrNn9GsvtYuQ3Gqn?p=preview

The functions don't work. The console tells me that web3.currentProvider.showPortis is not a function.

**Comment by tom-portis** [comment]
Hi @nceno , try doing it in a browser that doesn't have MetaMask 😄 

We need to fix the example, so the showPortis button will only show if web3 is undefined (i.e if Portis was set as the web3 provider).
You will see the getAccounts button works in both cases since it's a standard web3 function, supported both by MetaMask and Portis.

**Comment by radotzki** [comment]
Update the `plnkr`: https://plnkr.co/edit/vxaWCUlo8wSL91pvKUUB?p=preview
