### ISSUE TITLE
Issue on transferring of ether provided by portis

### ISSUE THREAD

**Issue by 071bctajay** [portis-project/portis-sdk#7]
0x965c58301bbbEF5D9bF1db5b70a0147f72f2FD24 (A) is the ethereum address I got from portis. I tried to sent $2 to 0x2e8E9a3dfA08792666c68D294387cF9F813322CB (B) this account. But after sending the amount it got automatically transferred to 0xFe60A20C40464b1f6c5bCD69cBd90F28E0609369 (C). Transactions can be viewed in ether scan.
Transaction from A to B - Block Height 6135552
Transaction from B to C - Block Height 6135554

Any idea on how that automatic transfer occurred?

**Comment by tomteman** [comment]
Hello Ajaya,

the account 0x2e8e9a3dfa08792666c68d294387cf9f813322cb (B) is a wallet which was not created with Portis, so once a transaction was made to account B, there is no way that Portis (or any other Ethereum account for that matter) can trigger an "automatic transfer" from an account it doesn't control to another. 
 
You can even see that the transaction (https://etherscan.io/tx/0xe6d90e3628232dbf2483e6bbaec2ca7a3e48d1f8ba13aac3591da53ab4205e48) was signed by account B. 

In general, since users maintain absolute control over their accounts, all transactions are signed by them, and there is no way for any action to take place without the account owner's explicit approval.
